modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/UpperMoon0/Geco/issues"
license = "MIT"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = "${mod_description}"
#logoFile = ""

[[dependencies.geco]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.172,21.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies.geco]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.21.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies.geco]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"
