name: Build and Release Mod

on:
  push:
    branches:
      - main 

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle' 

      - name: List gradle wrapper contents
        run: ls -la gradle/wrapper/

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Get Mod Version
        id: get_version
        run: |
          mod_version_line=$(grep 'mod_version = ' gradle.properties)
          mod_version=$(echo "$mod_version_line" | cut -d '=' -f 2 | xargs)
          echo "mod_version=$mod_version" >> $GITHUB_OUTPUT

      - name: Generate Release Tag
        id: tag_generator
        run: echo "tag_name=v${{ steps.get_version.outputs.mod_version }}" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag_generator.outputs.tag_name }}
          name: "Geco ${{ steps.tag_generator.outputs.tag_name }}"
          body: |
            Automatic release triggered by commit ${{ github.sha }} to the main branch.

            **Artifacts:**
            - Fabric Mod JAR
            - Forge Mod JAR
          draft: false
          prerelease: false
          files: |
            forge/build/libs/geco-forge-*.jar
            fabric/build/libs/geco-fabric-*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
